version: '3.4'

networks:
  user-manager-networks:
    driver: bridge

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      MSSQL_SA_PASSWORD: Fernando9+
      ACCEPT_EULA: Y
    container_name: sql-server
    networks:
      - user-manager-networks
    ports: 
      - 1433:1433

  usermanager:
    build:
      context: .
      dockerfile: ./UserManager/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=sql-server;Database=UserManager;User=sa;Password=Fernando9+;MultipleActiveResultSets=true;TrustServerCertificate=true;
    ports:
      - 46278:46278
      - 5210:5210
      - 7210:7210
      - 80:80
    container_name: usermanager
    depends_on:
      - sql-server
    networks:
      - user-manager-networks
